# MLProject/conda.yaml

name: mlproject-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - pip:
    - mlflow==2.22.1
    - pandas==2.2.3
    - numpy==1.26.0
    - scikit-learn==1.6.1 
