name: mlproject-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13 
  - pip
  - pandas==2.2.3
  - numpy==2.2.3
  - scikit-learn==1.6.1
  - matplotlib 
  - seaborn 
  - mlflow==2.22.1
