channels:
- conda-forge
dependencies:
- python=3.9.23
- pip<=25.1
- pip:
  - mlflow==2.13.0
  - cloudpickle==3.1.1
  - numpy==1.26.0
  - packaging==24.2
  - pyyaml==6.0.2
  - scikit-learn==1.5.1
  - scipy==1.13.1
name: mlflow-env
