# .github/workflows/ci_retrain.yml

name: CI - Retrain ML Model

on:
  push:
    branches:
      - main 
    paths:
      - 'MLProject/modelling_tuning.py'
      - 'MLProject/conda.yaml'
      - 'MLProject/MLProject'
      - 'MLProject/requirements.txt'
      - 'MLProject/telco_churn_preprocessing/**'
  workflow_dispatch:

jobs:
  retrain_model:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    env:
      DAGSHUB_REPO_NAME: CI-Workflow
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Conda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
          python-version: 3.9
          auto-activate-base: true
          activate-environment: mlproject-env
          environment-file: MLProject/conda.yaml

    - name: Install MLflow and DagsHub client
      run: |
        source "$(conda info --base)/etc/profile.d/conda.sh"
        conda activate mlproject-env
        
        python -m pip install --upgrade pip
        pip install mlflow==2.13.0 dagshub==0.5.10

        python -c "import dagshub; print('DagsHub version:', dagshub.__version__)"
        python -c "import mlflow; print('MLflow version:', mlflow.__version__)"

    - name: Configure DagsHub MLflow Tracking
      run: |
        echo "MLFLOW_TRACKING_URI=https://dagshub.com/hyrahmaaa/Workflow-CI.mlflow" >> "$GITHUB_ENV"
        echo "MLFLOW_TRACKING_USERNAME=hyrahmaaa" >> "$GITHUB_ENV"
        echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> "$GITHUB_ENV"
        echo "DAGSHUB_REPO_NAME=${{ github.event.repository.name }}" >> "$GITHUB_ENV"

