# .github/workflows/ci_retrain.yml

name: CI - Retrain ML Model

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/modelling_tuning.py'
      - 'MLProject/conda.yaml'
      - 'MLProject/MLProject'
      - 'MLProject/requirements.txt'
      - 'MLProject/telco_churn_preprocessing/**'
    workflow_dispatch:

  
