# .github/workflows/ci_retrain.yml

name: CI - Retrain ML Model

on:
  push:
    branches:
      - main 
    paths:
      - 'MLProject/modelling_tuning.py'
      - 'MLProject/conda.yaml'
      - 'MLProject/MLProject'
      - 'MLProject/requirements.txt'
      - 'MLProject/telco_churn_preprocessing/**'
  workflow_dispatch:

jobs:
  retrain_model:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    env:
      DAGSHUB_REPO_NAME: CI-Workflow
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Conda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
          python-version: 3.9
          auto-activate-base: true
          activate-environment: mlproject-env
          environment-file: MLProject/conda.yaml

    - name: Install MLflow and DagsHub client
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==3.1.0 dagshub==0.5.10
